import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {
  createPluginProjectSkillDeliveryReceipt,
  normalizeProjectSkillDeliveryReceipt,
  type ProjectSkillConflictStatus,
  type ProjectSkillDeliveryReceipt,
  type ProjectSkillRuntimeExportStatus,
  validateProjectSkillDeliveryReceipt,
} from '@alembic/core/host-agent-workflows';
import { pathGuard } from '@alembic/core/io';
import { resolveDataRoot, resolveProjectRoot } from '@alembic/core/workspace';
import { CODEX_HOST_AGENT_SOURCE } from '../runtime/SourceBoundary.js';

export const CODEX_PROJECT_SKILL_ROOT = path.join('.agents', 'skills');
export const PROJECT_SKILL_MARKER_FILE = '.alembic-managed.json';

interface ProjectSkillDeliveryContext {
  container?: {
    get?(name: string): unknown;
    singletons?: Record<string, unknown>;
  } | null;
}

export interface BuildPluginProjectSkillReceiptInput {
  contentHash?: string | null;
  description?: string | null;
  dimensionId?: string | null;
  evidenceRefs?: readonly unknown[];
  projectRoot?: string;
  skillName: string;
  sourcePath: string;
  targetName?: string | null;
}

export interface ProjectSkillRuntimeExportOptions {
  authorize?: boolean;
  grantedBy?: string;
  overwriteManaged?: boolean;
  receipt: unknown;
}

export interface ProjectSkillRuntimeExportResult {
  authorizationStatus: ProjectSkillDeliveryReceipt['authorization']['status'];
  conflictStatus: ProjectSkillConflictStatus;
  receipt: ProjectSkillDeliveryReceipt;
  runtimeExportStatus: ProjectSkillRuntimeExportStatus;
  targetPath: string | null;
}

export function getCodexProjectSkillRoot(projectRoot: string): string {
  return path.join(projectRoot, CODEX_PROJECT_SKILL_ROOT);
}

export function buildContentHash(content: string | Buffer): string {
  return `sha256:${crypto.createHash('sha256').update(content).digest('hex')}`;
}

export function buildProjectScopeId(projectRoot: string): string {
  return `project:${crypto.createHash('sha256').update(path.resolve(projectRoot)).digest('hex').slice(0, 12)}`;
}

export function buildGeneratedSkillId(projectScopeId: string, skillName: string): string {
  return `alembic:${projectScopeId}:${skillName}`;
}

export function buildPluginProjectSkillDeliveryReceipt(
  ctx: ProjectSkillDeliveryContext | null,
  input: BuildPluginProjectSkillReceiptInput
): ProjectSkillDeliveryReceipt {
  const projectRoot = input.projectRoot ?? resolveProjectRoot(ctx?.container as never);
  const projectScopeId = buildProjectScopeId(projectRoot);
  const codexSkillRoot = getCodexProjectSkillRoot(projectRoot);
  const sourcePath = path.resolve(input.sourcePath);
  const markerPath = path.join(codexSkillRoot, input.skillName, PROJECT_SKILL_MARKER_FILE);
  const contentHash =
    input.contentHash ??
    (fs.existsSync(sourcePath) ? buildContentHash(fs.readFileSync(sourcePath)) : null);

  return createPluginProjectSkillDeliveryReceipt({
    id: `plugin-skill-${projectScopeId.replace(/^project:/, '')}-${input.skillName}`,
    createdAt: new Date().toISOString(),
    projectRoot,
    projectScopeId,
    codexSkillRoot,
    projectId: projectScopeId,
    skillName: input.skillName,
    dimensionId: input.dimensionId ?? null,
    targetName: input.targetName ?? null,
    asset: {
      kind: 'skill-file',
      path: sourcePath,
      skillName: input.skillName,
      contentHash,
      description: input.description ?? null,
      dimensionId: input.dimensionId ?? null,
      targetName: input.targetName ?? null,
      artifactRefs: [{ kind: 'skill-file', ref: sourcePath }],
    },
    evidenceRefs: input.evidenceRefs ?? [],
    authorization: {
      required: true,
      status: 'pending',
      projectScopeId,
      codexSkillRoot,
      message: 'Codex project skill export needs project-scoped authorization.',
    },
    runtimeExport: {
      status: 'pending',
      strategy: 'symlink-first',
      linkMode: 'none',
      projectScopeId,
      codexSkillRoot,
      targetRoot: codexSkillRoot,
      targetPath: path.join(codexSkillRoot, input.skillName),
      refreshRequired: true,
    },
    managedMarker: {
      generatedSkillId: buildGeneratedSkillId(projectScopeId, input.skillName),
      generationHash: contentHash,
      markerPath,
      projectId: projectScopeId,
      projectRoot,
      projectScopeId,
      route: 'plugin',
      skillName: input.skillName,
      sourcePath,
    },
    shoutSummary: {
      delivered: false,
      runtimeVisible: false,
      skillName: input.skillName,
      title: 'Project Skill generated',
      trigger: input.skillName,
      message: `Project Skill ${input.skillName} generated by AlembicPlugin; Codex runtime export is pending.`,
    },
  });
}

export function exportProjectSkillReceiptToCodexRuntime(
  ctx: ProjectSkillDeliveryContext | null,
  options: ProjectSkillRuntimeExportOptions
): ProjectSkillRuntimeExportResult {
  const normalized = normalizeProjectSkillDeliveryReceipt(options.receipt);
  if (!normalized) {
    throw new Error('ProjectSkillDeliveryReceipt is required for runtime export.');
  }

  const projectRoot = resolveProjectRoot(ctx?.container as never);
  if (path.resolve(normalized.projectRoot) !== path.resolve(projectRoot)) {
    return finalizeReceipt(normalized, {
      authorizationStatus: normalized.authorization.status,
      conflictStatus: 'blocked',
      linkMode: 'none',
      message: `Receipt projectRoot does not match current Codex project root: ${normalized.projectRoot}`,
      runtimeExportStatus: 'blocked',
      targetPath: null,
    });
  }

  const sourceSkillPath = resolveSourceSkillPath(normalized);
  const codexSkillRoot = getCodexProjectSkillRoot(projectRoot);
  const projectScopeId =
    normalized.projectScopeId ||
    normalized.authorization.projectScopeId ||
    buildProjectScopeId(projectRoot);
  const targetDir = path.join(codexSkillRoot, normalized.skillName);
  const targetSkillPath = path.join(targetDir, 'SKILL.md');
  const markerPath = path.join(targetDir, PROJECT_SKILL_MARKER_FILE);
  const generationHash =
    normalized.managedMarker?.generationHash ||
    normalized.asset.contentHash ||
    (fs.existsSync(sourceSkillPath) ? buildContentHash(fs.readFileSync(sourceSkillPath)) : null);
  const generatedSkillId =
    normalized.managedMarker?.generatedSkillId ??
    buildGeneratedSkillId(projectScopeId, normalized.skillName);

  if (!options.authorize && normalized.authorization.status !== 'granted') {
    return finalizeReceipt(normalized, {
      authorizationStatus: 'pending',
      conflictStatus: 'blocked',
      linkMode: 'none',
      message:
        'Project-level authorization is required before exporting this Project Skill into Codex runtime.',
      runtimeExportStatus: 'blocked',
      targetPath: targetDir,
    });
  }

  if (!fs.existsSync(sourceSkillPath)) {
    return finalizeReceipt(normalized, {
      authorizationStatus: 'granted',
      conflictStatus: 'blocked',
      linkMode: 'none',
      message: `Source SKILL.md does not exist: ${sourceSkillPath}`,
      runtimeExportStatus: 'failed',
      targetPath: targetDir,
    });
  }

  const compatibility = inspectExistingRuntimeTarget({
    generationHash,
    generatedSkillId,
    markerPath,
    projectScopeId,
    sourceSkillPath,
    targetDir,
    targetSkillPath,
  });
  if (!compatibility.allowed) {
    return finalizeReceipt(normalized, {
      authorizationStatus: 'granted',
      conflictStatus: compatibility.conflictStatus,
      linkMode: 'none',
      message: compatibility.message,
      runtimeExportStatus: 'blocked',
      targetPath: targetDir,
    });
  }

  try {
    pathGuard.addProjectWritePrefix('.agents');
    pathGuard.assertSafe(sourceSkillPath);
    pathGuard.assertProjectWriteSafe(targetDir);
    pathGuard.assertProjectWriteSafe(targetSkillPath);
    pathGuard.assertProjectWriteSafe(markerPath);
    fs.mkdirSync(targetDir, { recursive: true });

    if (
      fs.existsSync(targetSkillPath) ||
      fs.lstatSync(targetSkillPath, { throwIfNoEntry: false })
    ) {
      if (compatibility.sameSymlink) {
        // 已经是同一 source 的 symlink，只刷新 marker 和 receipt 状态。
      } else if (options.overwriteManaged !== false && compatibility.managed) {
        fs.rmSync(targetSkillPath, { force: true });
      }
    }

    if (!fs.existsSync(targetSkillPath)) {
      fs.symlinkSync(sourceSkillPath, targetSkillPath, 'file');
    }

    const marker = {
      contractVersion: normalized.contractVersion,
      generatedSkillId,
      generationHash,
      managedBy: 'alembic',
      projectId: normalized.projectId ?? projectScopeId,
      projectRoot,
      projectScopeId,
      route: normalized.route,
      skillName: normalized.skillName,
      sourcePath: sourceSkillPath,
      markerPath,
      updatedAt: new Date().toISOString(),
    };
    fs.writeFileSync(markerPath, `${JSON.stringify(marker, null, 2)}\n`, 'utf8');
  } catch (err: unknown) {
    return finalizeReceipt(normalized, {
      authorizationStatus: 'granted',
      conflictStatus: 'blocked',
      linkMode: 'none',
      message: `Project Skill runtime export failed: ${err instanceof Error ? err.message : String(err)}`,
      runtimeExportStatus: 'failed',
      targetPath: targetDir,
    });
  }

  return finalizeReceipt(normalized, {
    authorizationStatus: 'granted',
    conflictStatus: compatibility.conflictStatus,
    linkMode: 'symlink',
    message: `Project Skill ${normalized.skillName} exported to Codex project runtime.`,
    runtimeExportStatus: 'exported',
    targetPath: targetDir,
  });
}

export function listProjectSkillDeliveryReceipts(
  ctx: ProjectSkillDeliveryContext | null
): ProjectSkillDeliveryReceipt[] {
  const dataRoot = resolveDataRoot(ctx?.container as never);
  const reportRoots = [
    path.join(dataRoot, '.asd', 'bootstrap-report.json'),
    path.join(dataRoot, '.asd', 'bootstrap-reports'),
  ];
  const receipts: ProjectSkillDeliveryReceipt[] = [];
  for (const reportRoot of reportRoots) {
    collectReceiptsFromPath(reportRoot, receipts);
  }
  return receipts;
}

export function findProjectSkillDeliveryReceipt(
  ctx: ProjectSkillDeliveryContext | null,
  selector: { name?: string; receipt?: unknown; receiptId?: string; skillName?: string }
): ProjectSkillDeliveryReceipt | null {
  if (selector.receipt) {
    return normalizeProjectSkillDeliveryReceipt(selector.receipt);
  }
  const name = selector.skillName || selector.name;
  const receipts = listProjectSkillDeliveryReceipts(ctx);
  return (
    receipts.find((receipt) => receipt.id === selector.receiptId) ??
    receipts.find((receipt) => (name ? receipt.skillName === name : false)) ??
    null
  );
}

function resolveSourceSkillPath(receipt: ProjectSkillDeliveryReceipt): string {
  const source = path.isAbsolute(receipt.asset.path)
    ? receipt.asset.path
    : path.resolve(receipt.projectRoot, receipt.asset.path);
  try {
    const stat = fs.statSync(source);
    return stat.isDirectory() ? path.join(source, 'SKILL.md') : source;
  } catch {
    return source.endsWith('SKILL.md') ? source : path.join(source, 'SKILL.md');
  }
}

function finalizeReceipt(
  receipt: ProjectSkillDeliveryReceipt,
  outcome: {
    authorizationStatus: ProjectSkillDeliveryReceipt['authorization']['status'];
    conflictStatus: ProjectSkillConflictStatus;
    linkMode: ProjectSkillDeliveryReceipt['runtimeExport']['linkMode'];
    message: string;
    runtimeExportStatus: ProjectSkillRuntimeExportStatus;
    targetPath: string | null;
  }
): ProjectSkillRuntimeExportResult {
  const targetRoot = outcome.targetPath
    ? path.dirname(outcome.targetPath)
    : receipt.runtimeExport.targetRoot;
  const updated = normalizeProjectSkillDeliveryReceipt({
    ...receipt,
    authorization: {
      ...receipt.authorization,
      status: outcome.authorizationStatus,
      grantedBy:
        outcome.authorizationStatus === 'granted'
          ? receipt.authorization.grantedBy || CODEX_HOST_AGENT_SOURCE
          : receipt.authorization.grantedBy,
      projectScopeId: receipt.authorization.projectScopeId || receipt.projectScopeId,
      codexSkillRoot: receipt.authorization.codexSkillRoot || targetRoot,
      message: outcome.message,
    },
    conflictStatus: outcome.conflictStatus,
    runtimeExport: {
      ...receipt.runtimeExport,
      authorizationStatus: outcome.authorizationStatus,
      conflictStatus: outcome.conflictStatus,
      status: outcome.runtimeExportStatus,
      linkMode: outcome.linkMode,
      strategy: 'symlink-first',
      targetPath: outcome.targetPath,
      targetRoot,
      projectScopeId: receipt.runtimeExport.projectScopeId || receipt.projectScopeId,
      codexSkillRoot: receipt.runtimeExport.codexSkillRoot || targetRoot,
      refreshRequired: outcome.runtimeExportStatus === 'exported',
      message: outcome.message,
    },
    shoutSummary: {
      ...receipt.shoutSummary,
      delivered: outcome.runtimeExportStatus === 'exported',
      runtimeVisible: outcome.runtimeExportStatus === 'exported',
      message: outcome.message,
      title:
        outcome.runtimeExportStatus === 'exported'
          ? 'Project Skill exported'
          : 'Project Skill export blocked',
    },
  });
  const finalReceipt = updated ?? receipt;
  return {
    authorizationStatus: finalReceipt.authorization.status,
    conflictStatus: finalReceipt.conflictStatus,
    receipt: finalReceipt,
    runtimeExportStatus: finalReceipt.runtimeExport.status,
    targetPath: finalReceipt.runtimeExport.targetPath,
  };
}

function inspectExistingRuntimeTarget(input: {
  generatedSkillId: string;
  generationHash: string | null;
  markerPath: string;
  projectScopeId: string;
  sourceSkillPath: string;
  targetDir: string;
  targetSkillPath: string;
}): {
  allowed: boolean;
  conflictStatus: ProjectSkillConflictStatus;
  managed: boolean;
  message: string;
  sameSymlink: boolean;
} {
  const targetDirStat = fs.lstatSync(input.targetDir, { throwIfNoEntry: false });
  if (targetDirStat && !targetDirStat.isDirectory()) {
    return {
      allowed: false,
      conflictStatus: 'different-existing',
      managed: false,
      message: `Codex Project Skill target exists but is not a directory: ${input.targetDir}`,
      sameSymlink: false,
    };
  }

  const targetStat = fs.lstatSync(input.targetSkillPath, { throwIfNoEntry: false });
  if (!targetStat) {
    return {
      allowed: true,
      conflictStatus: 'target-missing',
      managed: false,
      message: 'Codex Project Skill target is missing and can be exported.',
      sameSymlink: false,
    };
  }

  const marker = readManagedMarker(input.markerPath);
  const sameSymlink =
    targetStat.isSymbolicLink() &&
    path.resolve(fs.readlinkSync(input.targetSkillPath)) === path.resolve(input.sourceSkillPath);
  const markerCompatible =
    marker?.managedBy === 'alembic' &&
    marker.generatedSkillId === input.generatedSkillId &&
    marker.projectScopeId === input.projectScopeId &&
    (!input.generationHash || marker.generationHash === input.generationHash);

  if (markerCompatible || sameSymlink) {
    return {
      allowed: true,
      conflictStatus: 'compatible-existing',
      managed: markerCompatible,
      message: 'Existing Codex Project Skill target is compatible and may be refreshed.',
      sameSymlink,
    };
  }

  return {
    allowed: false,
    conflictStatus: 'different-existing',
    managed: false,
    message:
      `Codex Project Skill target already exists and is not managed by this receipt: ` +
      `${input.targetSkillPath}`,
    sameSymlink: false,
  };
}

function readManagedMarker(markerPath: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(markerPath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function collectReceiptsFromPath(pathname: string, receipts: ProjectSkillDeliveryReceipt[]): void {
  if (!fs.existsSync(pathname)) {
    return;
  }
  const stat = fs.statSync(pathname);
  if (stat.isDirectory()) {
    for (const entry of fs.readdirSync(pathname, { withFileTypes: true })) {
      if (entry.isDirectory() || entry.name.endsWith('.json')) {
        collectReceiptsFromPath(path.join(pathname, entry.name), receipts);
      }
    }
    return;
  }
  if (!pathname.endsWith('.json')) {
    return;
  }
  try {
    collectReceiptsFromValue(JSON.parse(fs.readFileSync(pathname, 'utf8')), receipts);
  } catch {
    /* ignore unreadable historical report */
  }
}

function collectReceiptsFromValue(value: unknown, receipts: ProjectSkillDeliveryReceipt[]): void {
  const direct = normalizeProjectSkillDeliveryReceipt(value);
  if (direct) {
    if (!receipts.some((receipt) => receipt.id === direct.id)) {
      receipts.push(direct);
    }
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      collectReceiptsFromValue(item, receipts);
    }
    return;
  }
  if (value && typeof value === 'object') {
    for (const item of Object.values(value as Record<string, unknown>)) {
      collectReceiptsFromValue(item, receipts);
    }
  }
}

export function validateReceiptForRuntimeExport(receipt: unknown) {
  const validation = validateProjectSkillDeliveryReceipt(receipt);
  if (!validation.ok) {
    return validation;
  }
  const normalized = validation.receipt;
  const issues = [...validation.issues];
  if (!normalized?.projectScopeId || !normalized?.authorization.projectScopeId) {
    issues.push('authorization-scope-missing' as const);
  }
  if (!normalized?.runtimeExport.projectScopeId || !normalized?.runtimeExport.codexSkillRoot) {
    issues.push('runtime-export-scope-missing' as const);
  }
  if (issues.length > validation.issues.length) {
    return {
      ...validation,
      issues,
      ok: false,
    };
  }
  return validation;
}
